app/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 6, max: 50, minMessage: 'Le titre doit faire au moins 6 caractères', maxMessage: 'Le titre doit faire au maximum 50 caractères')]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'articles')]
    private Collection $categories;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addArticle($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeArticle($this);
        }

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }
}

app/src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_comment = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    public function __construct()
    {
        $this->date_comment = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateComment(): ?\DateTimeInterface
    {
        return $this->date_comment;
    }

    public function setDateComment(\DateTimeInterface $date_comment): self
    {
        $this->date_comment = $date_comment;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
}

app/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use App\Service\VerificationComment;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class DefaultController extends AbstractController
{
    // Liste l'ensemble des articles
    #[Route('/', name: 'liste_articles',  methods: ['GET'])]
    public function listeArticles(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findBy([
            'state' => 'publie'
        ]);
        return $this->render('default/index.html.twig', ['articles' => $articles, 'brouillon' => false]);
    }

    // Afficher un article en particulier
    #[Route('/{id}', name: 'vue_article', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function vueArticle(Article $article, Request $request, EntityManagerInterface $manager, VerificationComment $verificationComment): Response
    {
        $session = $request->getSession();
        $comment = new Comment();
        $comment->setArticle($article);
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if (!$verificationComment->commentNonAuthorise($comment)) {
                $manager->persist($comment);
                $manager->flush();
                return $this->redirectToRoute('vue_article', ['id' => $article->getId()]);
            } else {
                $session->getFlashBag()->add("danger", "Le commentaire contient un mot interdit");
            }
        }

        return $this->render(
            'default/vue.html.twig',
            [
                'article' => $article,
                'form' => $form->createView()
            ]
        );
    }
}

app/templates/default/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article
{% endblock %}

{% block body %}
	{% if not form.vars.valid %}
		{{ form_start(form, {'attr':{'class': 'was-validated'}}) }}
	{% else %}
		{{ form_start(form) }}
	{% endif %}
	{{ form_errors(form) }}
	{{ form_label(form.titre, null, { 'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
	<div class="invalid-feedback">
		{{ form_errors(form.titre) }}
	</div>

	{{ form_label(form.contenu, null, { 'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}

	{{ form_label(form.date_creation, null, { 'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.date_creation, {'attr': {'class': 'form-control'}}) }}

	{{ form_label(form.categories, null, { 'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.categories, {'attr': {'class': 'form-control'}}) }}

	{{ form_widget(form.brouillon, {'attr': {'class': 'btn btn-default'}}) }}
	{{ form_widget(form.publier, {'attr': {'class': 'btn btn-success'}}) }}

	{{form_rest(form)}}

	{{ form_end(form) }}
{% endblock %}

app/templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles
{% endblock %}

{% block body %}
<h1>Articles
	{% if brouillon %}
		Brouillons
	{% endif %}! ✅</h1>
<ul>
	{% for article in articles %}
		<li>
			<a href="{{ path('vue_article', { 'id':article.id }) }}">{{ article.titre }}</a>
		</li>
	</a>
</li>{% endfor %}</ul>{% endblock %}

app/templates/default/vue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article numéro
	{{article.titre}}
{% endblock %}

{% block body %}
	<p>Article numéro
		{{ article.id }}</p>
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('edit_article', {'id': article.id}) }}" class="btn btn-info">Editer</a>
	{% endif %}
	<p>{{ article.dateCreation|date }}</p>
	<p>
		{{ article.contenu }}
	</p>
	<h2>
		Commentaires
	</h2>
	<div class="row">
		{%for comment in article.comments %}
			<div class="col-md-12">
				<p>{{ comment.dateComment|date }}</p>
				<p>{{ comment.author }}</p>
				<p>{{ comment.contenu }}</p>
			</div>
		{% endfor %}

		{% for label, messages in app.flashes(['warning', 'danger']) %}
			{% for message in messages %}
				<div class="alert alert-{{ label }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endfor %}

		{{ form_start(form) }}
		{{ form_label(form.contenu, null, { 'label_attr': {'class': 'form-label'}}) }}
		{{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}
		{{ form_label(form.author, null, { 'label_attr': {'class': 'form-label'}}) }}
		{{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
		<div class="form-checkbox">
			{{ form_widget(form.condition, {'attr': {'class': 'form-check-input'}}) }}
			{{ form_label(form.condition, null, { 'label_attr': {'class': 'form-check-label'}}) }}
		</div>
		{{ form_rest(form) }}
		<button type="submit" class="btn btn-primary">Enregistrer</button>
		{{ form_end(form) }}
	</div>
{% endblock %}